# CMake generated Testfile for 
# Source directory: /home/nao/Documents/Projects/reader
# Build directory: /home/nao/Documents/Projects/reader/build-qt
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test("core" "/home/nao/.local/lib/python3.14/site-packages/cmake/data/bin/cmake" "-DTEST_EXECUTABLE=/home/nao/Documents/Projects/reader/build-qt/test_core" "-DTEST_HOME_ROOT=/home/nao/Documents/Projects/reader/build-qt/test-homes" "-P" "/home/nao/Documents/Projects/reader/cmake/RunIsolatedTest.cmake")
set_tests_properties("core" PROPERTIES  _BACKTRACE_TRIPLES "/home/nao/Documents/Projects/reader/CMakeLists.txt;136;add_test;/home/nao/Documents/Projects/reader/CMakeLists.txt;0;")
add_test("chat_lifecycle" "/home/nao/.local/lib/python3.14/site-packages/cmake/data/bin/cmake" "-DTEST_EXECUTABLE=/home/nao/Documents/Projects/reader/build-qt/test_chat_lifecycle" "-DTEST_HOME_ROOT=/home/nao/Documents/Projects/reader/build-qt/test-homes" "-P" "/home/nao/Documents/Projects/reader/cmake/RunIsolatedTest.cmake")
set_tests_properties("chat_lifecycle" PROPERTIES  _BACKTRACE_TRIPLES "/home/nao/Documents/Projects/reader/CMakeLists.txt;144;add_test;/home/nao/Documents/Projects/reader/CMakeLists.txt;0;")
add_test("qt" "/home/nao/.local/lib/python3.14/site-packages/cmake/data/bin/cmake" "-DTEST_EXECUTABLE=/home/nao/Documents/Projects/reader/build-qt/test_qt" "-DTEST_HOME_ROOT=/home/nao/Documents/Projects/reader/build-qt/test-homes" "-P" "/home/nao/Documents/Projects/reader/cmake/RunIsolatedTest.cmake")
set_tests_properties("qt" PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen;LD_LIBRARY_PATH=/usr/lib64:/home/nao/qtsysroot/usr/lib64:/home/nao/miniforge3/lib" _BACKTRACE_TRIPLES "/home/nao/Documents/Projects/reader/CMakeLists.txt;156;add_test;/home/nao/Documents/Projects/reader/CMakeLists.txt;0;")
add_test("select" "/home/nao/.local/lib/python3.14/site-packages/cmake/data/bin/cmake" "-DTEST_EXECUTABLE=/home/nao/Documents/Projects/reader/build-qt/test_select" "-DTEST_HOME_ROOT=/home/nao/Documents/Projects/reader/build-qt/test-homes" "-P" "/home/nao/Documents/Projects/reader/cmake/RunIsolatedTest.cmake")
set_tests_properties("select" PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen;LD_LIBRARY_PATH=/usr/lib64:/home/nao/qtsysroot/usr/lib64:/home/nao/miniforge3/lib" _BACKTRACE_TRIPLES "/home/nao/Documents/Projects/reader/CMakeLists.txt;169;add_test;/home/nao/Documents/Projects/reader/CMakeLists.txt;0;")
add_test("chat_ui" "/home/nao/.local/lib/python3.14/site-packages/cmake/data/bin/cmake" "-DTEST_EXECUTABLE=/home/nao/Documents/Projects/reader/build-qt/test_chat_ui" "-DTEST_HOME_ROOT=/home/nao/Documents/Projects/reader/build-qt/test-homes" "-P" "/home/nao/Documents/Projects/reader/cmake/RunIsolatedTest.cmake")
set_tests_properties("chat_ui" PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen;LD_LIBRARY_PATH=/usr/lib64:/home/nao/qtsysroot/usr/lib64:/home/nao/miniforge3/lib" _BACKTRACE_TRIPLES "/home/nao/Documents/Projects/reader/CMakeLists.txt;181;add_test;/home/nao/Documents/Projects/reader/CMakeLists.txt;0;")
add_test("embedding_qt" "/home/nao/.local/lib/python3.14/site-packages/cmake/data/bin/cmake" "-DTEST_EXECUTABLE=/home/nao/Documents/Projects/reader/build-qt/test_embedding_qt" "-DTEST_HOME_ROOT=/home/nao/Documents/Projects/reader/build-qt/test-homes" "-P" "/home/nao/Documents/Projects/reader/cmake/RunIsolatedTest.cmake")
set_tests_properties("embedding_qt" PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen;LD_LIBRARY_PATH=/usr/lib64:/home/nao/qtsysroot/usr/lib64:/home/nao/miniforge3/lib" SKIP_REGULAR_EXPRESSION "embedding adapter test skipped" _BACKTRACE_TRIPLES "/home/nao/Documents/Projects/reader/CMakeLists.txt;190;add_test;/home/nao/Documents/Projects/reader/CMakeLists.txt;0;")
add_test("reader_ui" "/home/nao/.local/lib/python3.14/site-packages/cmake/data/bin/cmake" "-DTEST_EXECUTABLE=/home/nao/Documents/Projects/reader/build-qt/test_reader_ui" "-DTEST_HOME_ROOT=/home/nao/Documents/Projects/reader/build-qt/test-homes" "-P" "/home/nao/Documents/Projects/reader/cmake/RunIsolatedTest.cmake")
set_tests_properties("reader_ui" PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen;LD_LIBRARY_PATH=/usr/lib64:/home/nao/qtsysroot/usr/lib64:/home/nao/miniforge3/lib" _BACKTRACE_TRIPLES "/home/nao/Documents/Projects/reader/CMakeLists.txt;205;add_test;/home/nao/Documents/Projects/reader/CMakeLists.txt;0;")
add_test("render" "/home/nao/.local/lib/python3.14/site-packages/cmake/data/bin/cmake" "-DTEST_EXECUTABLE=/home/nao/Documents/Projects/reader/build-qt/test_render" "-DTEST_HOME_ROOT=/home/nao/Documents/Projects/reader/build-qt/test-homes" "-P" "/home/nao/Documents/Projects/reader/cmake/RunIsolatedTest.cmake")
set_tests_properties("render" PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen;LD_LIBRARY_PATH=/usr/lib64:/home/nao/qtsysroot/usr/lib64:/home/nao/miniforge3/lib" _BACKTRACE_TRIPLES "/home/nao/Documents/Projects/reader/CMakeLists.txt;216;add_test;/home/nao/Documents/Projects/reader/CMakeLists.txt;0;")
add_test("render_stress" "/home/nao/.local/lib/python3.14/site-packages/cmake/data/bin/cmake" "-DTEST_EXECUTABLE=/home/nao/Documents/Projects/reader/build-qt/test_render_stress" "-DTEST_HOME_ROOT=/home/nao/Documents/Projects/reader/build-qt/test-homes" "-P" "/home/nao/Documents/Projects/reader/cmake/RunIsolatedTest.cmake")
set_tests_properties("render_stress" PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen;LD_LIBRARY_PATH=/usr/lib64:/home/nao/qtsysroot/usr/lib64:/home/nao/miniforge3/lib" _BACKTRACE_TRIPLES "/home/nao/Documents/Projects/reader/CMakeLists.txt;227;add_test;/home/nao/Documents/Projects/reader/CMakeLists.txt;0;")
add_test("webengine" "/home/nao/.local/lib/python3.14/site-packages/cmake/data/bin/cmake" "-DTEST_EXECUTABLE=/home/nao/Documents/Projects/reader/build-qt/test_webengine" "-DTEST_HOME_ROOT=/home/nao/Documents/Projects/reader/build-qt/test-homes" "-P" "/home/nao/Documents/Projects/reader/cmake/RunIsolatedTest.cmake")
set_tests_properties("webengine" PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen;QTWEBENGINE_DISABLE_SANDBOX=1;QTWEBENGINE_CHROMIUM_FLAGS=--no-sandbox --disable-gpu;LD_LIBRARY_PATH=/usr/lib64:/home/nao/qtsysroot/usr/lib64:/home/nao/miniforge3/lib;QTWEBENGINEPROCESS_PATH=/home/nao/qtsysroot/usr/lib64/qt6/libexec/QtWebEngineProcess;QTWEBENGINE_RESOURCES_PATH=/home/nao/qtsysroot/usr/share/qt6/resources;QTWEBENGINE_LOCALES_PATH=/home/nao/qtsysroot/usr/share/qt6/translations/qtwebengine_locales;QTWEBENGINE_DICTIONARIES_PATH=/home/nao/qtsysroot/usr/share/qt6/qtwebengine_dictionaries" _BACKTRACE_TRIPLES "/home/nao/Documents/Projects/reader/CMakeLists.txt;242;add_test;/home/nao/Documents/Projects/reader/CMakeLists.txt;0;")
add_test("chat_rich" "/home/nao/.local/lib/python3.14/site-packages/cmake/data/bin/cmake" "-DTEST_EXECUTABLE=/home/nao/Documents/Projects/reader/build-qt/test_chat_rich" "-DTEST_HOME_ROOT=/home/nao/Documents/Projects/reader/build-qt/test-homes" "-P" "/home/nao/Documents/Projects/reader/cmake/RunIsolatedTest.cmake")
set_tests_properties("chat_rich" PROPERTIES  ENVIRONMENT "QT_QPA_PLATFORM=offscreen;QTWEBENGINE_DISABLE_SANDBOX=1;QTWEBENGINE_CHROMIUM_FLAGS=--no-sandbox --disable-gpu;LD_LIBRARY_PATH=/usr/lib64:/home/nao/qtsysroot/usr/lib64:/home/nao/miniforge3/lib;QTWEBENGINEPROCESS_PATH=/home/nao/qtsysroot/usr/lib64/qt6/libexec/QtWebEngineProcess;QTWEBENGINE_RESOURCES_PATH=/home/nao/qtsysroot/usr/share/qt6/resources;QTWEBENGINE_LOCALES_PATH=/home/nao/qtsysroot/usr/share/qt6/translations/qtwebengine_locales;QTWEBENGINE_DICTIONARIES_PATH=/home/nao/qtsysroot/usr/share/qt6/qtwebengine_dictionaries" _BACKTRACE_TRIPLES "/home/nao/Documents/Projects/reader/CMakeLists.txt;269;add_test;/home/nao/Documents/Projects/reader/CMakeLists.txt;0;")
