if(NOT DEFINED TEST_EXECUTABLE OR NOT DEFINED TEST_HOME_ROOT)
  message(FATAL_ERROR "RunIsolatedTest.cmake requires TEST_EXECUTABLE and TEST_HOME_ROOT")
endif()

file(MAKE_DIRECTORY "${TEST_HOME_ROOT}")
string(RANDOM LENGTH 24 ALPHABET 0123456789abcdef RUN_ID)
set(TEST_HOME "${TEST_HOME_ROOT}/home-${RUN_ID}")
while(EXISTS "${TEST_HOME}")
  string(RANDOM LENGTH 24 ALPHABET 0123456789abcdef RUN_ID)
  set(TEST_HOME "${TEST_HOME_ROOT}/home-${RUN_ID}")
endwhile()
file(MAKE_DIRECTORY "${TEST_HOME}")
set(ENV{HOME} "${TEST_HOME}")
set(ENV{XDG_CONFIG_HOME} "${TEST_HOME}/.config")
set(ENV{XDG_CACHE_HOME} "${TEST_HOME}/.cache")
set(ENV{XDG_DATA_HOME} "${TEST_HOME}/.local/share")
# Tests must remain offline and deterministic even when the developer shell
# carries credentials or provider overrides.
unset(ENV{OPENAI_API_KEY})
unset(ENV{PAPER_READER_MODEL})
unset(ENV{PAPER_READER_BASE_URL})
file(MAKE_DIRECTORY "$ENV{XDG_CONFIG_HOME}" "$ENV{XDG_CACHE_HOME}" "$ENV{XDG_DATA_HOME}")

execute_process(COMMAND "${TEST_EXECUTABLE}" RESULT_VARIABLE TEST_RESULT)
file(REMOVE_RECURSE "${TEST_HOME}")
if(TEST_RESULT EQUAL 77)
  message(STATUS "Isolated test skipped (exit code 77)")
  return()
endif()
if(NOT TEST_RESULT EQUAL 0)
  message(FATAL_ERROR "Isolated test failed with exit code ${TEST_RESULT}")
endif()
